version: "3.9"
services:
  streamer:
    build: .
    command: python services/device_streamer.py
    volumes:
      - .:/app
    ports:
      - 5555:8889

  consumer:
    build: .
    command: python services/device_consumer.py
    volumes:
      - .:/app
      - ../config.json:/config/config.json

    depends_on:
      - streamer

  producer:
    build: .
    command: python services/device_producer.py
    volumes:
      - .:/app
      - ../config.json:/config/config.json
    depends_on:
      - streamer
