version: "3.9"
services:
  streamer:
    build: .
    command: python services/device_streamer.py rm services/logs/streamer.log
    volumes:
      - .:/app

  consumer:
    build: .
    command: python services/device_consumer.py
    volumes:
      - .:/app
    depends_on:
      - streamer

  producer:
    build: .
    command: python services/device_producer.py
    volumes:
      - .:/app
      - ../config.json:/config/config.json
    depends_on:
      - streamer
